package com.wzsport.model;

public class ActivityDataCollection {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_activity_data_collection.id
     * @mbg.generated  Wed Nov 22 00:16:19 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_activity_data_collection.activity_id
     * @mbg.generated  Wed Nov 22 00:16:19 CST 2017
     */
    private Long activityId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_activity_data_collection.collection_data
     * @mbg.generated  Wed Nov 22 00:16:19 CST 2017
     */
    private String collectionData;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_activity_data_collection.id
     * @return  the value of wzsport_activity_data_collection.id
     * @mbg.generated  Wed Nov 22 00:16:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_activity_data_collection.id
     * @param id  the value for wzsport_activity_data_collection.id
     * @mbg.generated  Wed Nov 22 00:16:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_activity_data_collection.activity_id
     * @return  the value of wzsport_activity_data_collection.activity_id
     * @mbg.generated  Wed Nov 22 00:16:19 CST 2017
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_activity_data_collection.activity_id
     * @param activityId  the value for wzsport_activity_data_collection.activity_id
     * @mbg.generated  Wed Nov 22 00:16:19 CST 2017
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_activity_data_collection.collection_data
     * @return  the value of wzsport_activity_data_collection.collection_data
     * @mbg.generated  Wed Nov 22 00:16:19 CST 2017
     */
    public String getCollectionData() {
        return collectionData;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_activity_data_collection.collection_data
     * @param collectionData  the value for wzsport_activity_data_collection.collection_data
     * @mbg.generated  Wed Nov 22 00:16:19 CST 2017
     */
    public void setCollectionData(String collectionData) {
        this.collectionData = collectionData;
    }
}