package com.wzsport.model;

import java.util.Date;

public class AndroidVersionInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_android_version_info.id
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_android_version_info.version
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	private String version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_android_version_info.version_code
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	private Integer versionCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_android_version_info.changelog
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	private String changelog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_android_version_info.forced
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	private Boolean forced;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_android_version_info.apk_url
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	private String apkUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_android_version_info.created_at
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_android_version_info.updated_at
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_android_version_info.id
	 * @return  the value of wzsport_android_version_info.id
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_android_version_info.id
	 * @param id  the value for wzsport_android_version_info.id
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_android_version_info.version
	 * @return  the value of wzsport_android_version_info.version
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_android_version_info.version
	 * @param version  the value for wzsport_android_version_info.version
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_android_version_info.version_code
	 * @return  the value of wzsport_android_version_info.version_code
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public Integer getVersionCode() {
		return versionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_android_version_info.version_code
	 * @param versionCode  the value for wzsport_android_version_info.version_code
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public void setVersionCode(Integer versionCode) {
		this.versionCode = versionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_android_version_info.changelog
	 * @return  the value of wzsport_android_version_info.changelog
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public String getChangelog() {
		return changelog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_android_version_info.changelog
	 * @param changelog  the value for wzsport_android_version_info.changelog
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public void setChangelog(String changelog) {
		this.changelog = changelog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_android_version_info.forced
	 * @return  the value of wzsport_android_version_info.forced
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public Boolean getForced() {
		return forced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_android_version_info.forced
	 * @param forced  the value for wzsport_android_version_info.forced
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public void setForced(Boolean forced) {
		this.forced = forced;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_android_version_info.apk_url
	 * @return  the value of wzsport_android_version_info.apk_url
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public String getApkUrl() {
		return apkUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_android_version_info.apk_url
	 * @param apkUrl  the value for wzsport_android_version_info.apk_url
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public void setApkUrl(String apkUrl) {
		this.apkUrl = apkUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_android_version_info.created_at
	 * @return  the value of wzsport_android_version_info.created_at
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_android_version_info.created_at
	 * @param createdAt  the value for wzsport_android_version_info.created_at
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_android_version_info.updated_at
	 * @return  the value of wzsport_android_version_info.updated_at
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_android_version_info.updated_at
	 * @param updatedAt  the value for wzsport_android_version_info.updated_at
	 * @mbg.generated  Tue Jul 18 21:42:44 CST 2017
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}