package com.wzsport.model;

import java.util.Date;

public class FitnessCheckData {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fitness_check_data.id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fitness_check_data.student_id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Long studentId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fitness_check_data.term_id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Long termId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fitness_check_data.height
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Integer height;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fitness_check_data.weight
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Integer weight;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fitness_check_data.lung_capacity
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Integer lungCapacity;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fitness_check_data.BMI
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Double bmi;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fitness_check_data.created_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Date createdAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fitness_check_data.updated_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fitness_check_data.id
     * @return  the value of wzsport_fitness_check_data.id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fitness_check_data.id
     * @param id  the value for wzsport_fitness_check_data.id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fitness_check_data.student_id
     * @return  the value of wzsport_fitness_check_data.student_id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fitness_check_data.student_id
     * @param studentId  the value for wzsport_fitness_check_data.student_id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fitness_check_data.term_id
     * @return  the value of wzsport_fitness_check_data.term_id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Long getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fitness_check_data.term_id
     * @param termId  the value for wzsport_fitness_check_data.term_id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setTermId(Long termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fitness_check_data.height
     * @return  the value of wzsport_fitness_check_data.height
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fitness_check_data.height
     * @param height  the value for wzsport_fitness_check_data.height
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fitness_check_data.weight
     * @return  the value of wzsport_fitness_check_data.weight
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fitness_check_data.weight
     * @param weight  the value for wzsport_fitness_check_data.weight
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fitness_check_data.lung_capacity
     * @return  the value of wzsport_fitness_check_data.lung_capacity
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Integer getLungCapacity() {
        return lungCapacity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fitness_check_data.lung_capacity
     * @param lungCapacity  the value for wzsport_fitness_check_data.lung_capacity
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setLungCapacity(Integer lungCapacity) {
        this.lungCapacity = lungCapacity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fitness_check_data.BMI
     * @return  the value of wzsport_fitness_check_data.BMI
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Double getBmi() {
        return bmi;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fitness_check_data.BMI
     * @param bmi  the value for wzsport_fitness_check_data.BMI
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setBmi(Double bmi) {
        this.bmi = bmi;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fitness_check_data.created_at
     * @return  the value of wzsport_fitness_check_data.created_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fitness_check_data.created_at
     * @param createdAt  the value for wzsport_fitness_check_data.created_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fitness_check_data.updated_at
     * @return  the value of wzsport_fitness_check_data.updated_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fitness_check_data.updated_at
     * @param updatedAt  the value for wzsport_fitness_check_data.updated_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}