package com.wzsport.model;

import java.math.BigDecimal;
import java.util.Date;

// TODO: Auto-generated Javadoc
/**
 * The Class FixLocationOutdoorSportPoint.
 */
public class FixLocationOutdoorSportPoint {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fix_location_outdoor_sport_point.id
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fix_location_outdoor_sport_point.name
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fix_location_outdoor_sport_point.latitude
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	private BigDecimal latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fix_location_outdoor_sport_point.longitude
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	private BigDecimal longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fix_location_outdoor_sport_point.radius
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	private Byte radius;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fix_location_outdoor_sport_point.addr
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	private String addr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fix_location_outdoor_sport_point.university_id
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	private Integer universityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fix_location_outdoor_sport_point.description
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_fix_location_outdoor_sport_point.is_enable
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	private Boolean isEnable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fix_location_outdoor_sport_point.id
	 * @return  the value of wzsport_fix_location_outdoor_sport_point.id
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public Long getId() {
		return id;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fix_location_outdoor_sport_point.id
	 * @param id  the value for wzsport_fix_location_outdoor_sport_point.id
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fix_location_outdoor_sport_point.name
	 * @return  the value of wzsport_fix_location_outdoor_sport_point.name
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public String getName() {
		return name;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fix_location_outdoor_sport_point.name
	 * @param name  the value for wzsport_fix_location_outdoor_sport_point.name
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fix_location_outdoor_sport_point.latitude
	 * @return  the value of wzsport_fix_location_outdoor_sport_point.latitude
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public BigDecimal getLatitude() {
		return latitude;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fix_location_outdoor_sport_point.latitude
	 * @param latitude  the value for wzsport_fix_location_outdoor_sport_point.latitude
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fix_location_outdoor_sport_point.longitude
	 * @return  the value of wzsport_fix_location_outdoor_sport_point.longitude
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public BigDecimal getLongitude() {
		return longitude;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fix_location_outdoor_sport_point.longitude
	 * @param longitude  the value for wzsport_fix_location_outdoor_sport_point.longitude
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fix_location_outdoor_sport_point.radius
	 * @return  the value of wzsport_fix_location_outdoor_sport_point.radius
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public Byte getRadius() {
		return radius;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fix_location_outdoor_sport_point.radius
	 * @param radius  the value for wzsport_fix_location_outdoor_sport_point.radius
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public void setRadius(Byte radius) {
		this.radius = radius;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fix_location_outdoor_sport_point.addr
	 * @return  the value of wzsport_fix_location_outdoor_sport_point.addr
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public String getAddr() {
		return addr;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fix_location_outdoor_sport_point.addr
	 * @param addr  the value for wzsport_fix_location_outdoor_sport_point.addr
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fix_location_outdoor_sport_point.university_id
	 * @return  the value of wzsport_fix_location_outdoor_sport_point.university_id
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public Integer getUniversityId() {
		return universityId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fix_location_outdoor_sport_point.university_id
	 * @param universityId  the value for wzsport_fix_location_outdoor_sport_point.university_id
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public void setUniversityId(Integer universityId) {
		this.universityId = universityId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fix_location_outdoor_sport_point.description
	 * @return  the value of wzsport_fix_location_outdoor_sport_point.description
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public String getDescription() {
		return description;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fix_location_outdoor_sport_point.description
	 * @param description  the value for wzsport_fix_location_outdoor_sport_point.description
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_fix_location_outdoor_sport_point.is_enable
	 * @return  the value of wzsport_fix_location_outdoor_sport_point.is_enable
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public Boolean getIsEnable() {
		return isEnable;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_fix_location_outdoor_sport_point.is_enable
	 * @param isEnable  the value for wzsport_fix_location_outdoor_sport_point.is_enable
	 * @mbg.generated  Thu Jul 27 09:37:30 CST 2017
	 */
	public void setIsEnable(Boolean isEnable) {
		this.isEnable = isEnable;
	}


	/**
	 * Instantiates a new fix location outdoor sport point.
	 *
	 * @param latitude the latitude
	 * @param longitude the longitude
	 * @param name the name
	 * @param radius the radius
	 * @param universityId the university id
	 * @param desc the desc
	 */
    public FixLocationOutdoorSportPoint(double latitude, double longitude, String name, byte radius, int universityId, String desc) {
    	this.latitude = BigDecimal.valueOf(latitude);
    	this.longitude = BigDecimal.valueOf(longitude);
    	this.radius = radius;
    	this.name = name;
    	this.universityId = universityId;
    	this.description = desc;
    }
    
    
    /**
     * Instantiates a new fix location outdoor sport point.
     *
     * @param id the id
     * @param latitude the latitude
     * @param longitude the longitude
     * @param name the name
     * @param radius the radius
     * @param universityId the university id
     * @param desc the desc
     */
    public FixLocationOutdoorSportPoint(long id, double latitude, double longitude, String name, byte radius, int universityId, String desc) {
    	this.id = id;
    	this.latitude = BigDecimal.valueOf(latitude);
    	this.longitude = BigDecimal.valueOf(longitude);
    	this.radius = radius;
    	this.name = name;
    	this.universityId = universityId;
    	this.description = desc;
    }

	/**
	 * Instantiates a new fix location outdoor sport point.
	 */
	public FixLocationOutdoorSportPoint() {
	}
}
