package com.wzsport.model;

import java.util.Date;

public class RunningActivity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.id
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.project_id
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Long projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.student_id
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Long studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.distance
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Integer distance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.cost_time
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Integer costTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.target_time
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Integer targetTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.start_time
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.calories_consumed
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Integer caloriesConsumed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.qualified
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Boolean qualified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.created_at
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_running_activity.updated_at
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.id
	 * @return  the value of wzsport_running_activity.id
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.id
	 * @param id  the value for wzsport_running_activity.id
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.project_id
	 * @return  the value of wzsport_running_activity.project_id
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Long getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.project_id
	 * @param projectId  the value for wzsport_running_activity.project_id
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.student_id
	 * @return  the value of wzsport_running_activity.student_id
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Long getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.student_id
	 * @param studentId  the value for wzsport_running_activity.student_id
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setStudentId(Long studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.distance
	 * @return  the value of wzsport_running_activity.distance
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Integer getDistance() {
		return distance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.distance
	 * @param distance  the value for wzsport_running_activity.distance
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.cost_time
	 * @return  the value of wzsport_running_activity.cost_time
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Integer getCostTime() {
		return costTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.cost_time
	 * @param costTime  the value for wzsport_running_activity.cost_time
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setCostTime(Integer costTime) {
		this.costTime = costTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.target_time
	 * @return  the value of wzsport_running_activity.target_time
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Integer getTargetTime() {
		return targetTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.target_time
	 * @param targetTime  the value for wzsport_running_activity.target_time
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setTargetTime(Integer targetTime) {
		this.targetTime = targetTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.start_time
	 * @return  the value of wzsport_running_activity.start_time
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.start_time
	 * @param startTime  the value for wzsport_running_activity.start_time
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.calories_consumed
	 * @return  the value of wzsport_running_activity.calories_consumed
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Integer getCaloriesConsumed() {
		return caloriesConsumed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.calories_consumed
	 * @param caloriesConsumed  the value for wzsport_running_activity.calories_consumed
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setCaloriesConsumed(Integer caloriesConsumed) {
		this.caloriesConsumed = caloriesConsumed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.qualified
	 * @return  the value of wzsport_running_activity.qualified
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Boolean getQualified() {
		return qualified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.qualified
	 * @param qualified  the value for wzsport_running_activity.qualified
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setQualified(Boolean qualified) {
		this.qualified = qualified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.created_at
	 * @return  the value of wzsport_running_activity.created_at
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.created_at
	 * @param createdAt  the value for wzsport_running_activity.created_at
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_running_activity.updated_at
	 * @return  the value of wzsport_running_activity.updated_at
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_running_activity.updated_at
	 * @param updatedAt  the value for wzsport_running_activity.updated_at
	 * @mbg.generated  Fri Jun 16 10:13:10 CST 2017
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}