package com.wzsport.model;

public class StudentConsumeRank {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_consume_rank.id
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_consume_rank.student_id
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	private Long studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_consume_rank.student_name
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	private String studentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_consume_rank.avatar_url
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	private String avatarUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_consume_rank.kcal_consumed
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	private Long kcalConsumed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_consume_rank.university_id
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	private Long universityId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_consume_rank.id
	 * @return  the value of wzsport_student_consume_rank.id
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_consume_rank.id
	 * @param id  the value for wzsport_student_consume_rank.id
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_consume_rank.student_id
	 * @return  the value of wzsport_student_consume_rank.student_id
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public Long getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_consume_rank.student_id
	 * @param studentId  the value for wzsport_student_consume_rank.student_id
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public void setStudentId(Long studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_consume_rank.student_name
	 * @return  the value of wzsport_student_consume_rank.student_name
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public String getStudentName() {
		return studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_consume_rank.student_name
	 * @param studentName  the value for wzsport_student_consume_rank.student_name
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_consume_rank.avatar_url
	 * @return  the value of wzsport_student_consume_rank.avatar_url
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public String getAvatarUrl() {
		return avatarUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_consume_rank.avatar_url
	 * @param avatarUrl  the value for wzsport_student_consume_rank.avatar_url
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_consume_rank.kcal_consumed
	 * @return  the value of wzsport_student_consume_rank.kcal_consumed
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public Long getKcalConsumed() {
		return kcalConsumed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_consume_rank.kcal_consumed
	 * @param kcalConsumed  the value for wzsport_student_consume_rank.kcal_consumed
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public void setKcalConsumed(Long kcalConsumed) {
		this.kcalConsumed = kcalConsumed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_consume_rank.university_id
	 * @return  the value of wzsport_student_consume_rank.university_id
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public Long getUniversityId() {
		return universityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_consume_rank.university_id
	 * @param universityId  the value for wzsport_student_consume_rank.university_id
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	public void setUniversityId(Long universityId) {
		this.universityId = universityId;
	}
}