package com.wzsport.model;

import java.util.Date;

public class StudentSportConsumeStatistic {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.user_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Long userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.student_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Long studentId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.kcal_consumed
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Long kcalConsumed;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.cost_time
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Long costTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.class_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Long classId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.university_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Long universityId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.student_no
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private String studentNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.is_man
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Boolean isMan;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.name
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.avatar_url
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private String avatarUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.sport_date
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Date sportDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.major_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Long majorId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.college_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Long collegeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.grade
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private Integer grade;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.major_name
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private String majorName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic_new.college_name
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    private String collegeName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.id
     * @return  the value of wzsport_student_sport_consume_statistic_new.id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.id
     * @param id  the value for wzsport_student_sport_consume_statistic_new.id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.user_id
     * @return  the value of wzsport_student_sport_consume_statistic_new.user_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.user_id
     * @param userId  the value for wzsport_student_sport_consume_statistic_new.user_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.student_id
     * @return  the value of wzsport_student_sport_consume_statistic_new.student_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.student_id
     * @param studentId  the value for wzsport_student_sport_consume_statistic_new.student_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.kcal_consumed
     * @return  the value of wzsport_student_sport_consume_statistic_new.kcal_consumed
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Long getKcalConsumed() {
        return kcalConsumed;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.kcal_consumed
     * @param kcalConsumed  the value for wzsport_student_sport_consume_statistic_new.kcal_consumed
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setKcalConsumed(Long kcalConsumed) {
        this.kcalConsumed = kcalConsumed;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.cost_time
     * @return  the value of wzsport_student_sport_consume_statistic_new.cost_time
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Long getCostTime() {
        return costTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.cost_time
     * @param costTime  the value for wzsport_student_sport_consume_statistic_new.cost_time
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setCostTime(Long costTime) {
        this.costTime = costTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.class_id
     * @return  the value of wzsport_student_sport_consume_statistic_new.class_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.class_id
     * @param classId  the value for wzsport_student_sport_consume_statistic_new.class_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.university_id
     * @return  the value of wzsport_student_sport_consume_statistic_new.university_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.university_id
     * @param universityId  the value for wzsport_student_sport_consume_statistic_new.university_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.student_no
     * @return  the value of wzsport_student_sport_consume_statistic_new.student_no
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.student_no
     * @param studentNo  the value for wzsport_student_sport_consume_statistic_new.student_no
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.is_man
     * @return  the value of wzsport_student_sport_consume_statistic_new.is_man
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Boolean getIsMan() {
        return isMan;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.is_man
     * @param isMan  the value for wzsport_student_sport_consume_statistic_new.is_man
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setIsMan(Boolean isMan) {
        this.isMan = isMan;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.name
     * @return  the value of wzsport_student_sport_consume_statistic_new.name
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.name
     * @param name  the value for wzsport_student_sport_consume_statistic_new.name
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.avatar_url
     * @return  the value of wzsport_student_sport_consume_statistic_new.avatar_url
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.avatar_url
     * @param avatarUrl  the value for wzsport_student_sport_consume_statistic_new.avatar_url
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.sport_date
     * @return  the value of wzsport_student_sport_consume_statistic_new.sport_date
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Date getSportDate() {
        return sportDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.sport_date
     * @param sportDate  the value for wzsport_student_sport_consume_statistic_new.sport_date
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setSportDate(Date sportDate) {
        this.sportDate = sportDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.major_id
     * @return  the value of wzsport_student_sport_consume_statistic_new.major_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Long getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.major_id
     * @param majorId  the value for wzsport_student_sport_consume_statistic_new.major_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setMajorId(Long majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.college_id
     * @return  the value of wzsport_student_sport_consume_statistic_new.college_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Long getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.college_id
     * @param collegeId  the value for wzsport_student_sport_consume_statistic_new.college_id
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setCollegeId(Long collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.grade
     * @return  the value of wzsport_student_sport_consume_statistic_new.grade
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.grade
     * @param grade  the value for wzsport_student_sport_consume_statistic_new.grade
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.major_name
     * @return  the value of wzsport_student_sport_consume_statistic_new.major_name
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.major_name
     * @param majorName  the value for wzsport_student_sport_consume_statistic_new.major_name
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic_new.college_name
     * @return  the value of wzsport_student_sport_consume_statistic_new.college_name
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic_new.college_name
     * @param collegeName  the value for wzsport_student_sport_consume_statistic_new.college_name
     * @mbg.generated  Wed Jan 03 16:53:25 CST 2018
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }
}