package com.wzsport.model;

import java.util.Date;

public class StudentSportConsumeStatistic {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.user_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private Long userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.student_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private Long studentId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.kcal_consumed
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private Long kcalConsumed;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.cost_time
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private Long costTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.class_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private Long classId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.university_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private Long universityId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.student_no
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private String studentNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.is_man
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private Boolean isMan;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.name
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.avatar_url
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private String avatarUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.sport_date
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    private Date sportDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.major_id
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    private Long majorId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.college_id
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    private Long collegeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.grade
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    private Integer grade;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.major_name
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    private String majorName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_statistic.college_name
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    private String collegeName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.id
     * @return  the value of wzsport_student_sport_consume_statistic.id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.id
     * @param id  the value for wzsport_student_sport_consume_statistic.id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.user_id
     * @return  the value of wzsport_student_sport_consume_statistic.user_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.user_id
     * @param userId  the value for wzsport_student_sport_consume_statistic.user_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.student_id
     * @return  the value of wzsport_student_sport_consume_statistic.student_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.student_id
     * @param studentId  the value for wzsport_student_sport_consume_statistic.student_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.kcal_consumed
     * @return  the value of wzsport_student_sport_consume_statistic.kcal_consumed
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public Long getKcalConsumed() {
        return kcalConsumed;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.kcal_consumed
     * @param kcalConsumed  the value for wzsport_student_sport_consume_statistic.kcal_consumed
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setKcalConsumed(Long kcalConsumed) {
        this.kcalConsumed = kcalConsumed;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.cost_time
     * @return  the value of wzsport_student_sport_consume_statistic.cost_time
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public Long getCostTime() {
        return costTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.cost_time
     * @param costTime  the value for wzsport_student_sport_consume_statistic.cost_time
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setCostTime(Long costTime) {
        this.costTime = costTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.class_id
     * @return  the value of wzsport_student_sport_consume_statistic.class_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.class_id
     * @param classId  the value for wzsport_student_sport_consume_statistic.class_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.university_id
     * @return  the value of wzsport_student_sport_consume_statistic.university_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.university_id
     * @param universityId  the value for wzsport_student_sport_consume_statistic.university_id
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.student_no
     * @return  the value of wzsport_student_sport_consume_statistic.student_no
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.student_no
     * @param studentNo  the value for wzsport_student_sport_consume_statistic.student_no
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.is_man
     * @return  the value of wzsport_student_sport_consume_statistic.is_man
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public Boolean getIsMan() {
        return isMan;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.is_man
     * @param isMan  the value for wzsport_student_sport_consume_statistic.is_man
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setIsMan(Boolean isMan) {
        this.isMan = isMan;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.name
     * @return  the value of wzsport_student_sport_consume_statistic.name
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.name
     * @param name  the value for wzsport_student_sport_consume_statistic.name
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.avatar_url
     * @return  the value of wzsport_student_sport_consume_statistic.avatar_url
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.avatar_url
     * @param avatarUrl  the value for wzsport_student_sport_consume_statistic.avatar_url
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.sport_date
     * @return  the value of wzsport_student_sport_consume_statistic.sport_date
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public Date getSportDate() {
        return sportDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.sport_date
     * @param sportDate  the value for wzsport_student_sport_consume_statistic.sport_date
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
=======
     * @mbg.generated  Sun Nov 12 14:24:13 CST 2017
>>>>>>> 3ac524975058... see #1124_8
=======
     * @mbg.generated  Wed Nov 15 16:43:59 CST 2017
>>>>>>> 0d22cc3d6c22... see f_1124_15
=======
     * @mbg.generated  Wed Nov 15 19:25:35 CST 2017
>>>>>>> f56a08fb9d4a... see f_1139_1
=======
     * @mbg.generated  Thu Nov 16 22:47:22 CST 2017
>>>>>>> d053db385567... see f_1139_2
=======
     * @mbg.generated  Fri Nov 17 14:37:24 CST 2017
>>>>>>> 2913deae1992... see f_1124_17
     */
    public void setSportDate(Date sportDate) {
        this.sportDate = sportDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.major_id
     * @return  the value of wzsport_student_sport_consume_statistic.major_id
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public Long getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.major_id
     * @param majorId  the value for wzsport_student_sport_consume_statistic.major_id
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public void setMajorId(Long majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.college_id
     * @return  the value of wzsport_student_sport_consume_statistic.college_id
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public Long getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.college_id
     * @param collegeId  the value for wzsport_student_sport_consume_statistic.college_id
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public void setCollegeId(Long collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.grade
     * @return  the value of wzsport_student_sport_consume_statistic.grade
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.grade
     * @param grade  the value for wzsport_student_sport_consume_statistic.grade
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.major_name
     * @return  the value of wzsport_student_sport_consume_statistic.major_name
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.major_name
     * @param majorName  the value for wzsport_student_sport_consume_statistic.major_name
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_statistic.college_name
     * @return  the value of wzsport_student_sport_consume_statistic.college_name
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_statistic.college_name
     * @param collegeName  the value for wzsport_student_sport_consume_statistic.college_name
     * @mbg.generated  Sun Nov 05 18:23:19 CST 2017
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }
}