package com.wzsport.model;

import java.util.Date;

public class StudentSportConsumeDailyStatistic {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_daily_statistic.id
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_daily_statistic.student_id
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    private Long studentId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_daily_statistic.sport_type
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    private Byte sportType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_daily_statistic.kcal_consumed
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    private Long kcalConsumed;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_daily_statistic.cost_time
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    private Long costTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_student_sport_consume_daily_statistic.sport_date
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    private Date sportDate;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_daily_statistic.id
     * @return  the value of wzsport_student_sport_consume_daily_statistic.id
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_daily_statistic.id
     * @param id  the value for wzsport_student_sport_consume_daily_statistic.id
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_daily_statistic.student_id
     * @return  the value of wzsport_student_sport_consume_daily_statistic.student_id
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_daily_statistic.student_id
     * @param studentId  the value for wzsport_student_sport_consume_daily_statistic.student_id
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_daily_statistic.sport_type
     * @return  the value of wzsport_student_sport_consume_daily_statistic.sport_type
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public Byte getSportType() {
        return sportType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_daily_statistic.sport_type
     * @param sportType  the value for wzsport_student_sport_consume_daily_statistic.sport_type
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public void setSportType(Byte sportType) {
        this.sportType = sportType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_daily_statistic.kcal_consumed
     * @return  the value of wzsport_student_sport_consume_daily_statistic.kcal_consumed
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public Long getKcalConsumed() {
        return kcalConsumed;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_daily_statistic.kcal_consumed
     * @param kcalConsumed  the value for wzsport_student_sport_consume_daily_statistic.kcal_consumed
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public void setKcalConsumed(Long kcalConsumed) {
        this.kcalConsumed = kcalConsumed;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_daily_statistic.cost_time
     * @return  the value of wzsport_student_sport_consume_daily_statistic.cost_time
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public Long getCostTime() {
        return costTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_daily_statistic.cost_time
     * @param costTime  the value for wzsport_student_sport_consume_daily_statistic.cost_time
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public void setCostTime(Long costTime) {
        this.costTime = costTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_student_sport_consume_daily_statistic.sport_date
     * @return  the value of wzsport_student_sport_consume_daily_statistic.sport_date
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public Date getSportDate() {
        return sportDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_student_sport_consume_daily_statistic.sport_date
     * @param sportDate  the value for wzsport_student_sport_consume_daily_statistic.sport_date
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    public void setSportDate(Date sportDate) {
        this.sportDate = sportDate;
    }
}