package com.wzsport.model;

import java.util.Date;

public class University {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_university.id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_university.name
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_university.created_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Date createdAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_university.updated_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_university.id
     * @return  the value of wzsport_university.id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_university.id
     * @param id  the value for wzsport_university.id
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_university.name
     * @return  the value of wzsport_university.name
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_university.name
     * @param name  the value for wzsport_university.name
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_university.created_at
     * @return  the value of wzsport_university.created_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_university.created_at
     * @param createdAt  the value for wzsport_university.created_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_university.updated_at
     * @return  the value of wzsport_university.updated_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_university.updated_at
     * @param updatedAt  the value for wzsport_university.updated_at
<<<<<<< HEAD
     * @mbg.generated  Tue Oct 03 15:25:05 CST 2017
=======
     * @mbg.generated  Sat Oct 07 23:32:43 CST 2017
>>>>>>> f_1035
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}