package com.wzsport.model;

import java.util.Date;
import java.util.List;

public class User {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_user.id
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_user.user_name
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_user.password
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_user.university_id
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	private Long universityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_user.latest_token
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	private String latestToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_user.created_at
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wzsport_user.updated_at
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_user.id
	 * @return  the value of wzsport_user.id
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_user.id
	 * @param id  the value for wzsport_user.id
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_user.user_name
	 * @return  the value of wzsport_user.user_name
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_user.user_name
	 * @param userName  the value for wzsport_user.user_name
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_user.password
	 * @return  the value of wzsport_user.password
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_user.password
	 * @param password  the value for wzsport_user.password
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_user.university_id
	 * @return  the value of wzsport_user.university_id
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public Long getUniversityId() {
		return universityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_user.university_id
	 * @param universityId  the value for wzsport_user.university_id
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public void setUniversityId(Long universityId) {
		this.universityId = universityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_user.latest_token
	 * @return  the value of wzsport_user.latest_token
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public String getLatestToken() {
		return latestToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_user.latest_token
	 * @param latestToken  the value for wzsport_user.latest_token
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public void setLatestToken(String latestToken) {
		this.latestToken = latestToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_user.created_at
	 * @return  the value of wzsport_user.created_at
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_user.created_at
	 * @param createdAt  the value for wzsport_user.created_at
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wzsport_user.updated_at
	 * @return  the value of wzsport_user.updated_at
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wzsport_user.updated_at
	 * @param updatedAt  the value for wzsport_user.updated_at
	 * @mbg.generated  Mon Aug 07 15:48:13 CST 2017
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * 用户的角色集合
	 */
	private List<Role> roles;
	
    public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}
}