package com.wzsport.mapper;

import com.wzsport.model.ActivityDataStatistic;
import com.wzsport.model.ActivityDataStatisticExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ActivityDataStatisticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    long countByExample(ActivityDataStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    int deleteByExample(ActivityDataStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    @Delete({
        "delete from wzsport_activity_data_statistic",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    @Insert({
        "insert into wzsport_activity_data_statistic (activity_id, data_count, ",
        "speed_against, distance_per_step_against)",
        "values (#{activityId,jdbcType=BIGINT}, #{dataCount,jdbcType=INTEGER}, ",
        "#{speedAgainst,jdbcType=INTEGER}, #{distancePerStepAgainst,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ActivityDataStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    int insertSelective(ActivityDataStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    List<ActivityDataStatistic> selectByExample(ActivityDataStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    @Select({
        "select",
        "id, activity_id, data_count, speed_against, distance_per_step_against",
        "from wzsport_activity_data_statistic",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.wzsport.mapper.ActivityDataStatisticMapper.BaseResultMap")
    ActivityDataStatistic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") ActivityDataStatistic record, @Param("example") ActivityDataStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    int updateByExample(@Param("record") ActivityDataStatistic record, @Param("example") ActivityDataStatisticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    int updateByPrimaryKeySelective(ActivityDataStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wzsport_activity_data_statistic
     *
     * @mbg.generated Wed Nov 15 19:25:35 CST 2017
     */
    @Update({
        "update wzsport_activity_data_statistic",
        "set activity_id = #{activityId,jdbcType=BIGINT},",
          "data_count = #{dataCount,jdbcType=INTEGER},",
          "speed_against = #{speedAgainst,jdbcType=INTEGER},",
          "distance_per_step_against = #{distancePerStepAgainst,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ActivityDataStatistic record);
}