package com.wzsport.mapper;

import com.wzsport.model.SignIn;
import com.wzsport.model.SignInExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SignInMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	long countByExample(SignInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	int deleteByExample(SignInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	@Delete({ "delete from wzsport_sign_in", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	@Insert({ "insert into wzsport_sign_in (activity_id, student_id, ", "sign_in_time)",
			"values (#{activityId,jdbcType=BIGINT}, #{studentId,jdbcType=BIGINT}, ",
			"#{signInTime,jdbcType=TIMESTAMP})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(SignIn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	int insertSelective(SignIn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	List<SignIn> selectByExample(SignInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	@Select({ "select", "id, activity_id, student_id, sign_in_time", "from wzsport_sign_in",
			"where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.wzsport.mapper.SignInMapper.BaseResultMap")
	SignIn selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SignIn record, @Param("example") SignInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	int updateByExample(@Param("record") SignIn record, @Param("example") SignInExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	int updateByPrimaryKeySelective(SignIn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_sign_in
	 * @mbg.generated  Mon Aug 28 23:39:37 CST 2017
	 */
	@Update({ "update wzsport_sign_in", "set activity_id = #{activityId,jdbcType=BIGINT},",
			"student_id = #{studentId,jdbcType=BIGINT},", "sign_in_time = #{signInTime,jdbcType=TIMESTAMP}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(SignIn record);
}