package com.wzsport.mapper;

import com.wzsport.dto.StudentTimeCostedDTO;
import com.wzsport.model.StudentTimecostedRank;
import com.wzsport.model.StudentTimecostedRankExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface StudentTimecostedRankMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	long countByExample(StudentTimecostedRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int deleteByExample(StudentTimecostedRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	@Delete({ "delete from wzsport_student_timecosted_rank", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	@Insert({ "insert into wzsport_student_timecosted_rank (student_id, student_name, ", "avatar_url, cost_time, ",
			"university_id)", "values (#{studentId,jdbcType=BIGINT}, #{studentName,jdbcType=VARCHAR}, ",
			"#{avatarUrl,jdbcType=VARCHAR}, #{costTime,jdbcType=BIGINT}, ", "#{universityId,jdbcType=BIGINT})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(StudentTimecostedRank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int insertSelective(StudentTimecostedRank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	List<StudentTimecostedRank> selectByExample(StudentTimecostedRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	@Select({ "select", "id, student_id, student_name, avatar_url, cost_time, university_id",
			"from wzsport_student_timecosted_rank", "where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.wzsport.mapper.StudentTimecostedRankMapper.BaseResultMap")
	StudentTimecostedRank selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StudentTimecostedRank record,
			@Param("example") StudentTimecostedRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int updateByExample(@Param("record") StudentTimecostedRank record,
			@Param("example") StudentTimecostedRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int updateByPrimaryKeySelective(StudentTimecostedRank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_timecosted_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	@Update({ "update wzsport_student_timecosted_rank", "set student_id = #{studentId,jdbcType=BIGINT},",
			"student_name = #{studentName,jdbcType=VARCHAR},", "avatar_url = #{avatarUrl,jdbcType=VARCHAR},",
			"cost_time = #{costTime,jdbcType=BIGINT},", "university_id = #{universityId,jdbcType=BIGINT}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(StudentTimecostedRank record);

//	List<StudentTimecostedRank> getTimeCostedRanking(StudentTimecostedRankExample example);
	
	@Select("SELECT student_id, student_name,avatar_url, cost_time AS time_costed, university_id\n" +
			"FROM wzsport_student_timecosted_rank\n" +
			"WHERE university_id = #{universityId}\n" )
	List<StudentTimeCostedDTO> getTimeCostedRanking(@Param("universityId") long universityId);
}