package com.wzsport.mapper;

import com.wzsport.dto.StudentKcalConsumptionDTO;
import com.wzsport.dto.StudentTimeCostedDTO;
import com.wzsport.model.StudentConsumeRank;
import com.wzsport.model.StudentConsumeRankExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface StudentConsumeRankMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	long countByExample(StudentConsumeRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int deleteByExample(StudentConsumeRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	@Delete({ "delete from wzsport_student_consume_rank", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	@Insert({ "insert into wzsport_student_consume_rank (student_id, student_name, ", "avatar_url, kcal_consumed, ",
			"university_id)", "values (#{studentId,jdbcType=BIGINT}, #{studentName,jdbcType=VARCHAR}, ",
			"#{avatarUrl,jdbcType=VARCHAR}, #{kcalConsumed,jdbcType=BIGINT}, ", "#{universityId,jdbcType=BIGINT})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(StudentConsumeRank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int insertSelective(StudentConsumeRank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	List<StudentConsumeRank> selectByExample(StudentConsumeRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	@Select({ "select", "id, student_id, student_name, avatar_url, kcal_consumed, university_id",
			"from wzsport_student_consume_rank", "where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.wzsport.mapper.StudentConsumeRankMapper.BaseResultMap")
	StudentConsumeRank selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StudentConsumeRank record,
			@Param("example") StudentConsumeRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int updateByExample(@Param("record") StudentConsumeRank record,
			@Param("example") StudentConsumeRankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	int updateByPrimaryKeySelective(StudentConsumeRank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_consume_rank
	 * @mbg.generated  Mon May 28 16:50:53 CST 2018
	 */
	@Update({ "update wzsport_student_consume_rank", "set student_id = #{studentId,jdbcType=BIGINT},",
			"student_name = #{studentName,jdbcType=VARCHAR},", "avatar_url = #{avatarUrl,jdbcType=VARCHAR},",
			"kcal_consumed = #{kcalConsumed,jdbcType=BIGINT},", "university_id = #{universityId,jdbcType=BIGINT}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(StudentConsumeRank record);
	
	
    @Select("SELECT student_id, student_name,avatar_url, kcal_consumed AS kcal_consumption, university_id\n" +
            "FROM wzsport_student_consume_rank\n" +
            "WHERE university_id =  #{universityId}\n")
    List<StudentKcalConsumptionDTO> getKcalCostedRanking(@Param("universityId") long universityId);

}