package com.wzsport.mapper;

import com.wzsport.model.StudentSportConsumeDailyStatistic;
import com.wzsport.model.StudentSportConsumeDailyStatisticExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface StudentSportConsumeDailyStatisticMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    long countByExample(StudentSportConsumeDailyStatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    int deleteByExample(StudentSportConsumeDailyStatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    @Delete({ "delete from wzsport_student_sport_consume_daily_statistic", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    @Insert({ "insert into wzsport_student_sport_consume_daily_statistic (student_id, sport_type, ",
            "kcal_consumed, cost_time, ", "sport_date)",
            "values (#{studentId,jdbcType=BIGINT}, #{sportType,jdbcType=TINYINT}, ",
            "#{kcalConsumed,jdbcType=BIGINT}, #{costTime,jdbcType=BIGINT}, ", "#{sportDate,jdbcType=DATE})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(StudentSportConsumeDailyStatistic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    int insertSelective(StudentSportConsumeDailyStatistic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    List<StudentSportConsumeDailyStatistic> selectByExample(StudentSportConsumeDailyStatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    @Select({ "select", "id, student_id, sport_type, kcal_consumed, cost_time, sport_date",
            "from wzsport_student_sport_consume_daily_statistic", "where id = #{id,jdbcType=BIGINT}" })
    @ResultMap("com.wzsport.mapper.StudentSportConsumeDailyStatisticMapper.BaseResultMap")
    StudentSportConsumeDailyStatistic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") StudentSportConsumeDailyStatistic record,
            @Param("example") StudentSportConsumeDailyStatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    int updateByExample(@Param("record") StudentSportConsumeDailyStatistic record,
            @Param("example") StudentSportConsumeDailyStatisticExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    int updateByPrimaryKeySelective(StudentSportConsumeDailyStatistic record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wzsport_student_sport_consume_daily_statistic
     * @mbg.generated  Mon Oct 30 11:57:50 CST 2017
     */
    @Update({ "update wzsport_student_sport_consume_daily_statistic", "set student_id = #{studentId,jdbcType=BIGINT},",
            "sport_type = #{sportType,jdbcType=TINYINT},", "kcal_consumed = #{kcalConsumed,jdbcType=BIGINT},",
            "cost_time = #{costTime,jdbcType=BIGINT},", "sport_date = #{sportDate,jdbcType=DATE}",
            "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(StudentSportConsumeDailyStatistic record);

    @Select("SELECT student_id, 0 as sport_type, SUM(cost_time) AS cost_time, SUM(kcal_consumed) AS kcal_consumed, "
            + "date(start_time) as sport_date FROM wzsport_running_activity "
            + "WHERE date(start_time) >= date(#{start}) AND date(start_time) <= date(#{end}) AND is_valid = 1 GROUP BY student_id, date(start_time)")
    List<StudentSportConsumeDailyStatistic> getRunningSportDailyList(@Param("start") Date start, @Param("end") Date end);
    
    @Select("SELECT student_id, 1 as sport_type, SUM(cost_time) AS cost_time, SUM(kcal_consumed) AS kcal_consumed, "
            + "date(start_time) as sport_date FROM wzsport_area_activity "
            + "WHERE date(start_time) >= date(#{start}) AND date(start_time) <= date(#{end}) GROUP BY student_id, date(start_time)")
    List<StudentSportConsumeDailyStatistic> getAreaSportDailyList(@Param("start")Date start, @Param("end")Date end);
}